//
//  File.swift
//
//
//  Created by Tim Mewe on 14.01.20.
//

import SwiftProtobuf
import SwiftProtobufPluginLibrary

class Generator {
    private var printer: CodePrinter
    internal var file: FileDescriptor
    internal var service: ServiceDescriptor! // context during generation
    internal let protobufNamer: SwiftProtobufNamer

    init(_ file: FileDescriptor) {
        self.file = file
        printer = CodePrinter()
        protobufNamer = SwiftProtobufNamer(
            currentFile: file,
            protoFileToModuleMappings: ProtoFileToModuleMappings()
        )

        printMain()
    }

    func printMain() {
        printer.print("""
        //
        // DO NOT EDIT.
        //
        // Generated by the protocol buffer compiler.
        // Source: \(file.name)
        //
        """)

        let moduleNames = [
            "Grebe_Framework"
        ]

        for service in file.services {
            self.service = service
            printGrebe()
        }
    }
}
