name: PublishDocumentation
on: [push]
jobs:
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@v1.1.1
      with:
        personal_access_token: 8baa3f375328780bd3d69dbfbcfccb5a0ca3bca1
